### ISSUE TITLE
Codeflare Image not replaced in Manifests

### ISSUE THREAD

**Issue by VaishnaviHire** [opendatahub-io/codeflare-operator#15]
Codeflare when deployed with ODH operator, gives following error 

```
Failed to apply default image tag "$(odh-codeflare-operator-controller-image)": couldn't parse image reference "$(odh-codeflare-operator-controller-image)": invalid reference format
```

This is because image reference is not added to params.yaml file - https://github.com/opendatahub-io/codeflare-operator/blob/main/config/manifests/bases/params.yaml#L1

**Comment by VaishnaviHire** [comment]
Also need to update manifests/ kustomization.yaml with image reference

E.g https://github.com/opendatahub-io/data-science-pipelines-operator/blob/main/config/base/kustomization.yaml

**Comment by zdtsw** [comment]
fixed in https://github.com/opendatahub-io/codeflare-operator/pull/16

**Comment by sutaakar** [comment]
Fixed, closing.
