### ISSUE TITLE
Fix CodeFlare Operator history

### ISSUE THREAD

**Issue by anishasthana** [opendatahub-io/codeflare-operator#19]
ODH/CFO's git history has greatly diverged from upstream CFO. We should fix this before changes start to compound.

**Comment by dimakis** [comment]
We've got to maintain a set of patches. There should only be a handful of commits/ patches.

We could keep all of our patches on a seperate branch, then we rebase the patch branch on top of `main` after we sync ODH-CFO with PCF-CFO

**Comment by astefanutti** [comment]
Force pushed today for the v1.0.1 release, with manual rebase on top of PCF/CFO so the history is clean again. We should devise a branching strategy that performs it automatically.

**Comment by sutaakar** [comment]
Adjusted commit history to be better structured and follow common naming conventions.

**Comment by sutaakar** [comment]
Automation is tracked in https://issues.redhat.com/browse/RHOAIENG-1976
